"""旅行 CRUD（管理端）：嵌套集合、slug、校验、级联。"""

from tests.conftest import CITY_CODES, create_member, create_tag, create_trip, trip_payload


# ---------- 创建 ----------

def test_create_minimal_trip_defaults(client):
    r = client.post(
        "/api/v1/admin/trips",
        json={
            "title": "周末杭州",
            "start_date": "2022-06-04",
            "end_date": "2022-06-05",
        },
    )
    assert r.status_code == 201, r.text
    trip = r.json()
    assert trip["status"] == "draft"  # 默认草稿
    assert trip["slug"]  # 自动生成
    assert trip["route"] == []
    assert trip["days_count"] == 2


def test_slug_autogenerated_from_chinese_title(client):
    trip = create_trip(client, title="云南环线", cities=[], attractions=[], days=[])
    assert trip["slug"] == "yun-nan-huan-xian"


def test_slug_collision_appends_suffix(client):
    a = create_trip(client, title="云南环线", cities=[], attractions=[], days=[])
    b = create_trip(client, title="云南环线", cities=[], attractions=[], days=[], start_date="2023-05-01", end_date="2023-05-02")
    assert a["slug"] == "yun-nan-huan-xian"
    assert b["slug"] == "yun-nan-huan-xian-2"


def test_slug_custom_valid(client):
    trip = create_trip(client, slug="yunnan-2024", cities=[])
    assert trip["slug"] == "yunnan-2024"


def test_slug_custom_invalid_characters(client):
    r = client.post("/api/v1/admin/trips", json={"title": "x", "slug": "Bad Slug!", "start_date": "2024-01-01", "end_date": "2024-01-01"})
    assert r.status_code == 422


def test_slug_fallback_when_title_is_symbols(client):
    trip = create_trip(client, title="!!!", cities=[])
    assert trip["slug"].startswith("trip-")


def test_end_before_start_rejected(client):
    r = client.post(
        "/api/v1/admin/trips",
        json={"title": "x", "start_date": "2024-05-07", "end_date": "2024-05-01"},
    )
    assert r.status_code == 422


def test_status_only_draft_or_published(client):
    r = client.post(
        "/api/v1/admin/trips",
        json={"title": "x", "start_date": "2024-01-01", "end_date": "2024-01-01", "status": "archived"},
    )
    assert r.status_code == 422


def test_create_with_nested_collections(client):
    dad = create_member(client, "张三", nickname="爸爸")
    son = create_member(client, "张小四", nickname="哥哥", is_child=True)
    tag1 = create_tag(client, "亲子")
    tag2 = create_tag(client, "自驾")

    trip = create_trip(client, member_ids=[dad["id"], son["id"]], tag_ids=[tag1["id"], tag2["id"]])

    assert [m["nickname"] for m in trip["members"]] == ["爸爸", "哥哥"]
    assert [t["name"] for t in trip["tags"]] == ["亲子", "自驾"]
    assert [c["display"] for c in trip["cities"]] == ["昆明", "大理", "丽江"]
    assert [c["sort_order"] for c in trip["cities"]] == [0, 1, 2]
    assert [d["day_index"] for d in trip["trip_days"]] == [1, 2]
    assert trip["trip_days"][0]["title"] == "海埂大坝喂红嘴鸥"
    assert trip["attractions"][0]["name"] == "滇池 · 海埂大坝"


def test_create_foreign_trip_city_free_text(client):
    trip = create_trip(
        client,
        title="落樱时节，又逢君",
        country="日本",
        cities=[{"city_name": "京都", "lng": 135.8, "lat": 35.03}, {"city_name": "大阪"}],
        attractions=[{"name": "哲学之道", "note": "樱吹雪落了满肩。"}],
    )
    kyoto = trip["cities"][0]
    assert kyoto["city_code"] is None
    assert kyoto["city_name"] == "京都"
    assert kyoto["lng"] == 135.8
    assert trip["country"] == "日本"
    # 境外景点无字典城市 → resolved 坐标为空（不上中国地图）
    assert trip["attractions"][0]["resolved_lng"] is None


def test_unknown_city_code_422(client):
    r = client.post("/api/v1/admin/trips", json=trip_payload(cities=[{"city_code": "999999"}]))
    assert r.status_code == 422


def test_unknown_member_422(client):
    r = client.post("/api/v1/admin/trips", json=trip_payload(member_ids=[999]))
    assert r.status_code == 422


def test_unknown_tag_422(client):
    r = client.post("/api/v1/admin/trips", json=trip_payload(tag_ids=[999]))
    assert r.status_code == 422


def test_city_without_code_and_name_422(client):
    r = client.post("/api/v1/admin/trips", json=trip_payload(cities=[{"lng": 1.0, "lat": 2.0}]))
    assert r.status_code == 422


# ---------- 更新（整体替换嵌套集合） ----------

def test_update_replaces_nested_collections(client):
    tag = create_tag(client, "高原")
    member = create_member(client, "赵六")
    trip = create_trip(client, tag_ids=[tag["id"]])

    new_payload = trip_payload(
        title="改成青岛赶海",
        start_date="2023-08-12",
        end_date="2023-08-15",
        cities=[{"city_code": CITY_CODES["青岛市"]}],
        attractions=[{"name": "礁石滩", "city_code": CITY_CODES["青岛市"], "note": "带回一只寄居蟹。"}],
        days=[{"date": "2023-08-12", "title": "赶海"}],
        member_ids=[member["id"]],
        tag_ids=[],
    )
    r = client.put(f"/api/v1/admin/trips/{trip['id']}", json=new_payload)
    assert r.status_code == 200, r.text
    updated = r.json()

    assert updated["title"] == "改成青岛赶海"
    assert updated["tags"] == []
    assert [c["display"] for c in updated["cities"]] == ["青岛"]
    assert [a["name"] for a in updated["attractions"]] == ["礁石滩"]
    assert updated["members"][0]["name"] == "赵六"
    # slug 未提供时保持不变
    assert updated["slug"] == trip["slug"]


def test_update_can_change_slug_with_suffix_on_collision(client):
    a = create_trip(client, title="云南环线", cities=[])
    b = create_trip(client, title="另一次", cities=[])
    r = client.put(f"/api/v1/admin/trips/{b['id']}", json=trip_payload(title="另一次", slug=a["slug"], cities=[]))
    assert r.status_code == 200
    assert r.json()["slug"] == f"{a['slug']}-2"


def test_update_404(client):
    r = client.put("/api/v1/admin/trips/999", json=trip_payload())
    assert r.status_code == 404


# ---------- 删除与级联 ----------

def test_delete_trip_cascades_children(client, db):
    from sqlalchemy import text

    trip = create_trip(client)
    trip_id = trip["id"]
    r = client.delete(f"/api/v1/admin/trips/{trip_id}")
    assert r.status_code == 204

    for table in ("trip_city", "trip_day", "attraction", "trip_member", "trip_tag", "trip"):
        n = db.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar()
        assert n == 0, table


def test_delete_trip_404(client):
    assert client.delete("/api/v1/admin/trips/999").status_code == 404


# ---------- 管理端列表与筛选（user story 13） ----------

def test_admin_list_includes_drafts_and_filters(client):
    create_trip(client, title="2024 云南", start_date="2024-05-01", end_date="2024-05-07", tag_ids=[create_tag(client, "亲子")["id"]])
    create_trip(client, title="2023 青岛", start_date="2023-08-12", end_date="2023-08-15", cities=[{"city_code": CITY_CODES["青岛市"]}], status="draft")

    all_trips = client.get("/api/v1/admin/trips").json()
    assert len(all_trips) == 2  # 管理端可见草稿

    assert len(client.get("/api/v1/admin/trips", params={"status": "draft"}).json()) == 1
    assert len(client.get("/api/v1/admin/trips", params={"year": 2024}).json()) == 1
    assert len(client.get("/api/v1/admin/trips", params={"tag": "亲子"}).json()) == 1
    q = client.get("/api/v1/admin/trips", params={"q": "青岛"}).json()
    assert [t["title"] for t in q] == ["2023 青岛"]
